name: Test and Build Workflow

on:
  workflow_dispatch:  # Manuell trigger för att köra workflowet

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GREETING: "Running tests"
      NAME: "App"
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "$GREETING for $NAME..."
          pytest

  build:
    runs-on: ubuntu-latest
    needs: test  # Detta jobb körs bara om `test` jobbat klarar sig
    env:
      BUILD_GREETING: "Building the app"
      BUILD_NAME: "App"
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the app
        run: |
          echo "$BUILD_GREETING: $BUILD_NAME is being built."
          # Här kan du lägga till byggkommandon för din app
