name: Multi-Jobs Workflow

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:  # Lägger till manuell trigger

jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hello"
      NAME: "World"
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Print greeting
        run: echo "$GREETING, $NAME!"

      - name: Access a secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "The secret is $MY_SECRET"

  second-job:
    runs-on: ubuntu-latest
    needs: first-job  # Gör detta jobb beroende av `first-job`
    env:
      FAREWELL: "Goodbye"
      NAME: "World"
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Print farewell
        run: echo "$FAREWELL, $NAME!"
